services:
  - type: web
    name: datadepot-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -b 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 --preload
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: ENABLE_WEB_SEARCH
        value: "1"
      - key: WEB_MODEL
        value: "gpt-4.1-mini"
      - key: CORS_ORIGINS
        value: "http://localhost:3000,https://your-frontend-domain.com"
